### ISSUE TITLE
HICO-DET Zero-Shot Problem

### ISSUE THREAD

**Issue by kkayla99** [ltttpku/ADA-CM#13]
When I run 'unseen verb' like this:
```
python main_tip_finetune.py \
--world-size 1 \
--batch-size 8 \
--lr-head 1e-3 \
--lr-vit 1e-3 \
--pretrained checkpoints/detr-r50-hicodet.pth \
--output-dir checkpoints/hico_test \
--use_insadapter \
--num_classes 117 \
--use_multi_hot \
--file1 hicodet_pkl_files/union_embeddings_cachemodel_crop_padding_zeros_vitb16.p \
--clip_dir_vit checkpoints/pretrained_clip/ViT-B-16.pt \
--zs \
--zs_type unseen_verb
```
I got this error:
```
[INFO]: num_classes 117
Load weights for the object detector from checkpoints/detr-r50-hicodet.pth
[INFO] missing_keys: []
[INFO] unexpected_keys: []
Initializing a generic context
Initial context: "X X X X X X X X X X X X X X X X X X X X X X X X"
Number of context words (tokens): 24
[INFO]: missing idxs of verbs: [2, 19, 26, 34, 38, 41, 42, 56, 62, 76, 79, 80, 84, 91, 92, 97, 99, 100, 106, 114]
117it [00:00, 148.56it/s]
[INFO]: missing idxs of verbs: [2, 19, 26, 34, 38, 41, 42, 56, 62, 76, 79, 80, 84, 91, 92, 97, 99, 100, 106, 114, 2, 19, 26, 34, 38, 41, 42, 56, 62, 76, 79, 80, 84, 91, 92, 97, 99, 100, 106, 114]
2it [00:00, 79.69it/s]
Traceback (most recent call last):
  File "/opt/ADA-CM-main/main_tip_finetune.py", line 658, in <module>
    main(0,args)
  File "/opt/ADA-CM-main/main_tip_finetune.py", line 278, in main
    upt = build_detector(args, object_to_target, object_n_verb_to_interaction=object_n_verb_to_interaction, clip_model_path=args.clip_dir_vit, num_anno=num_anno, verb2interaction=verb2interaction)
  File "/opt/ADA-CM-main/upt_tip_cache_model_free_finetune_distill3.py", line 1511, in build_detector
    detector = UPT(args,
  File "/opt/ADA-CM-main/upt_tip_cache_model_free_finetune_distill3.py", line 346, in __init__
    self.cache_model_U, self.one_hots_U, self.sample_lens_U = self.load_cache_model(file1=file1, feature='uni',num_classes=self.num_classes, num_shot=num_shot, filtered_hoi_idx = self.filtered_hoi_idx, use_multi_hot=self.use_mul
ti_hot, label_choice=self.label_choice, num_anno=self.num_anno)
  File "/opt/ADA-CM-main/upt_tip_cache_model_free_finetune_distill3.py", line 686, in load_cache_model
    real_v = real_v[topk_idx]
IndexError: index is out of bounds for dimension with size 0
```
Can u help me about this?

**Comment by ltttpku** [comment]
Thanks for your interest in our work!
Please add the following two lines of code after [this line](https://github.com/ltttpku/ADA-CM/blob/main/upt_tip_cache_model_free_finetune_distill3.py#L604):
```
real_verbs[i].append(np.zeros(categories)) 
real_verbs[i][-1][i] = 1
```
These lines will append one-hot vectors for each `real_verbs[i]` corresponding to unseen verbs.

**Comment by kkayla99** [comment]
> Thanks for your interest in our work! Please add the following two lines of code after [this line](https://github.com/ltttpku/ADA-CM/blob/main/upt_tip_cache_model_free_finetune_distill3.py#L604):
> 
> ```
> real_verbs[i].append(np.zeros(categories)) 
> real_verbs[i][-1][i] = 1
> ```
> 
> These lines will append one-hot vectors for each `real_verbs[i]` corresponding to unseen verbs.

Thx for your quick reply!
Is anything else I need to pay attention to regarding this in other zero-shot setting (UC, UO, ...)?

**Comment by ltttpku** [comment]
In our [ICCV paper](https://openaccess.thecvf.com/content/ICCV2023/papers/Lei_Efficient_Adaptive_Human-Object_Interaction_Detection_with_Concept-guided_Memory_ICCV_2023_paper.pdf), we focus solely on the RF-UC and NF-UC settings, where all configurations should work as expected. If you encounter any issues with other settings, please don't hesitate to contact us.
