### ISSUE TITLE
About Fine Tuning Mode

### ISSUE THREAD

**Issue by echo-654** [ltttpku/ADA-CM#2]
您好！ 我已经成功运行了Training-Free Mode，但在进行微调训练时，我遇到了以下错误，请问您知道如何解决吗？

Traceback (most recent call last):
  File "/root/ADA-CM-main/main_tip_finetune.py", line 661, in <module>
    main(0,args)
  File "/root/ADA-CM-main/main_tip_finetune.py", line 452, in main
    engine(args.epochs)
  File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 136, in __call__
    self._on_start_iteration()
  File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 171, in _on_start_iteration
    self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True)
  File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 63, in relocate_to_cuda
    return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x]
  File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 63, in <listcomp>
    return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x]
  File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 70, in relocate_to_cuda
    x[key] = relocate_to_cuda(x[key], ignore, device, **kwargs)
  File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 75, in relocate_to_cuda
    raise TypeError('Unsupported type of data {}'.format(type(x)))
TypeError: Unsupported type of data <class 'str'>

**Comment by soberguo** [comment]
I had the same problem, I solved it by changing false under file (/root/ADA-CM-main/pocket/pocket/ops/relocate.py,line35) to true

**Comment by echo-654** [comment]
number of leanable params: 2119055
number of all params: 168018657
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
tensor(0, device='cuda:0') 3
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/ADA-CM-main/main_tip_finetune.py", line 661, in <module>
    main(0,args)
  File "/root/ADA-CM-main/main_tip_finetune.py", line 452, in main
^C  File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 139, in __call__
    self._on_each_iteration()
  File "/root/ADA-CM-main/utils_tip_cache_and_union_finetune.py", line 362, in _on_each_iteration
    loss_dict = self._state.net(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/ADA-CM-main/upt_tip_cache_model_free_finetune_distill3.py", line 1388, in forward
    interaction_loss = self.compute_interaction_loss(boxes, bh, bo, logits, prior, targets, gt_feats, pair_feats)
  File "/root/ADA-CM-main/upt_tip_cache_model_free_finetune_distill3.py", line 1026, in compute_interaction_loss
    logits = torch.cat(logits) 
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

Thank you for your answer. Have you encountered the above problems?

**Comment by ltttpku** [comment]
Thank you for your interest in our work! It appears that the variable "logits" contains an empty list of Tensors, which might be caused by the incorrect weight initialization of DETR. 
Please ensure that you have successfully loaded the pre-trained weights for DETR.

**Comment by yuchen2199** [comment]
I'm having the same problem, however I'm sure I've loaded the pre-trained weights for DETR correctly. 

Can you help me with this issue? Thanks!!!

**Comment by ltttpku** [comment]
That might be an issue related to the `batch size`. Using a small `batch size` can also lead to empty `logits` during training.

Can you try using larger `batch size` for training?

**Comment by xue2015210194** [comment]
> 您好！ 我已经成功运行了Training-Free Mode，但在进行微调训练时，我遇到了以下错误，请问您知道如何解决吗？
> 
> Traceback (most recent call last): File "/root/ADA-CM-main/main_tip_finetune.py", line 661, in main(0,args) File "/root/ADA-CM-main/main_tip_finetune.py", line 452, in main engine(args.epochs) File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 136, in **call** self._on_start_iteration() File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 171, in _on_start_iteration self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True) File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 63, in relocate_to_cuda return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x] File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 63, in return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x] File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 70, in relocate_to_cuda x[key] = relocate_to_cuda(x[key], ignore, device, **kwargs) File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 75, in relocate_to_cuda raise TypeError('Unsupported type of data {}'.format(type(x))) TypeError: Unsupported type of data <class 'str'>

请问您这个问题解决了吗？我也遇到了同样的问题

**Comment by xue2015210194** [comment]
> try using larger `batch size` for training

 I have tried to use larger batch size for training, but it does not work. Could you help me with this issue? Thanks!

**Comment by xue2015210194** [comment]
> try using larger `batch size` for training

 I have tried to use larger batch size for training, but it does not work. Could you help me with this issue? Thanks!

**Comment by ltttpku** [comment]
Can you check if the pretrained weights are placed in the right place as shown [here](https://github.com/ltttpku/ADA-CM?tab=readme-ov-file#pre-extracted-features)?

**Comment by xue2015210194** [comment]
> Can you check if the pretrained weights are placed in the right place as shown [here](https://github.com/ltttpku/ADA-CM?tab=readme-ov-file#pre-extracted-features)?

Traceback (most recent call last): File "/root/ADA-CM-main/main_tip_finetune.py", line 661, in main(0,args) File "/root/ADA-CM-main/main_tip_finetune.py", line 452, in main engine(args.epochs) File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 136, in call self._on_start_iteration() File "/root/ADA-CM-main/pocket/pocket/core/distributed.py", line 171, in _on_start_iteration self._state.targets = relocate_to_cuda(self._state.targets, non_blocking=True) File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 63, in relocate_to_cuda return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x] File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 63, in return [relocate_to_cuda(item, ignore, device, **kwargs) for item in x] File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 70, in relocate_to_cuda x[key] = relocate_to_cuda(x[key], ignore, device, **kwargs) File "/root/ADA-CM-main/pocket/pocket/ops/relocate.py", line 75, in relocate_to_cuda raise TypeError('Unsupported type of data {}'.format(type(x))) TypeError: Unsupported type of data <class 'str'>

I am sure that the pretrained weights are placed in the right place. And the training-free model can run correctly, but the fine-tuning model encountered the above problems.

**Comment by ltttpku** [comment]
According to the error `relocate_to_cuda raise TypeError('Unsupported type of data {}'.format(type(x))) TypeError: Unsupported type of data <class 'str'>`, you may need to modify the `relocate_to_cuda` function to avoid load `str` to cuda. The function should be located in `pocket.ops`.
